### ISSUE TITLE
Build process - step by step

### ISSUE THREAD

**Issue by pawellen** [zeliard/GameLift#4]
1) Can You add info how to create and upload build to Amazon GameLift? 
2) Can You also add example of a shell script file named "install.sh"and/or "install.bat"  which are located at the root of the build folder and used in this example.
I can't find anywhere detailed, easy to understand, descriptions how to prepare this "install.sh" file and how go threw whole build and upload process.
Help :)

**Comment by zeliard** [comment]
Hi, 
I'm sorry for late response.

1. For build uploads, see step 3 of this tutorial:
https://s3.amazonaws.com/gamedev-tutorials/Tutorials/GameLift-Getting_started-(03)_Uploading_your_server_build_1.8.pdf

2. Not always necessary for the install script.
You can just put the game server binaries and related files in one folder. If you want to install a dependable package, you need to create install.bat. See the tutorial step 4 below for instructions on writing an install script.
https://s3.amazonaws.com/gamedev-tutorials/Tutorials/GameLift-Getting_started-(02)_Packaging_your_server_build_1.8.pdf

Thanks!
